name: workflow-demo
run-name: ${{ github.actor }} esta corriendo este workflow
on: [push]
jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "prueba de la primera linea"
      - run: echo "evento ${{ github.event_name }}"
      - run: echo "quien es el runner ${{ runner.os }}""
      - run: echo "esta es la branch ${{ github.ref }}"